[tool.poetry]
name = "search-for-combinations"
version = "0.0.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
